#Require latest Vagrant

Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

#We assume that we have our own private registry for docker.

  config.vm.box = "testing/coreos"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
